services:
  www: 
    build: .
    ports:
      - "82:80"
      
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb:11.8.1-rc 
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: universidad
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    volumes:
      - ./base_datos:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.2

    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55